// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardCarouselController from "./card_carousel_controller"
application.register("card-carousel", CardCarouselController)

import FadeInController from "./fade_in_controller"
application.register("fade-in", FadeInController)

import FadeToggleController from "./fade_toggle_controller"
application.register("fade-toggle", FadeToggleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomePagesController from "./home_pages_controller"
application.register("home-pages", HomePagesController)

import PdiController from "./pdi_controller"
application.register("pdi", PdiController)
